## Custom app launcher

# screenshot
bindsym Print exec flameshot gui

# sublime text
bindsym $mod+n exec subl


# firefox
bindsym $mod+Shift+b exec --no-startup-id firefox --new-window

# chromium
bindsym $mod+b exec --no-startup-id chromium --new-window

# obsidian
bindsym $mod+Shift+o exec obsidian

# wallpaper
bindsym $mod+Ctrl+space exec ~/.local/share/yi3/script/wallpaper.sh