# ── Raccourcis Copier/Coller (Méthode officielle Omarchy) ─────────────────
bindsym --release $mod+c exec "xdotool key --clearmodifiers ctrl+Insert"
bindsym --release $mod+v exec "xdotool key --clearmodifiers shift+Insert"
bindsym --release $mod+x exec "xdotool key --clearmodifiers ctrl+x"

# Brightness
bindsym XF86MonBrightnessUp exec --no-startup-id brightnessctl set +10%
bindsym XF86MonBrightnessDown exec --no-startup-id brightnessctl set 5%-

# Volume
bindsym XF86AudioRaiseVolume exec pactl set-sink-volume @DEFAULT_SINK@ +10%
bindsym XF86AudioLowerVolume exec pactl set-sink-volume @DEFAULT_SINK@ -10%
bindsym XF86AudioMute exec pactl set-sink-mute @DEFAULT_SINK@ toggle