# i3blocks config file
# Doc: http://vivien.github.io/i3blocks

# Global Param
separator=false
separator_block_width=15
markup=pango

[CPU]
command=echo "<span color='#00F3FF'>󰻠 </span>$(~/.local/share/yi3/script/cpu_useage.sh)"
interval=5
color=#ffffff

[memory]
command=echo "<span color='#FF0055'>󰍛 </span>$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
interval=5
color=#ffffff

[disk]
command=echo "<span color='#E0AF68'>󰋊 </span>$(df -h / | awk 'NR==2 {print $3 "/" $2}')"
interval=3600
color=#ffffff

[bluetooth]
command=echo "<span color='#53BDFA'>󰂯 </span>$(if [ "$BLOCK_BUTTON" = "1" ]; then alacritty -t 'Bluetooth' -e bluetui & fi; systemctl is-active --quiet bluetooth && echo 'On' || echo 'Off')"
interval=10
color=#ffffff

[wifi]
command=echo "<span color='#90E1C6'>󰖩 </span>$(if [ "$BLOCK_BUTTON" = "1" ]; then alacritty -t 'Network' -e impala & fi; iwgetid -r || echo 'Down')"
interval=5
color=#ffffff

[volume]
command=echo "<span color='#FAE994'>󰕾 </span>$(if [ "$BLOCK_BUTTON" = "1" ]; then alacritty -t 'Volume' -e wiremix & fi; wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -dc '0-9.' | awk '{print int($1 * 100)"%"}')"
interval=1
color=#ffffff

[battery]
command=echo "<span color='#91B362'>󰁹 </span>$(cat /sys/class/power_supply/BAT*/capacity 2>/dev/null | head -n 1 | awk '{print $1"%"}' || echo 'AC')"
interval=60
color=#ffffff
